"""Deployment utilities for ALICE Engine MLflow models.

Provides MLflow model registration and Render deployment configuration.

ISO Compliance:
- ISO/IEC 42001:2023 - AI Management (Model Registry)
- ISO/IEC 5055:2021 - Code Quality

Author: ALICE Engine Team
Version: 1.0.0
"""

from __future__ import annotations

import logging

# Features: canonical source is scripts.training.features (DRY - ISO 24027)
from scripts.training.features import CATEGORICAL_FEATURES, NUMERIC_FEATURES

logger = logging.getLogger(__name__)


def register_model_to_mlflow(
    model_path: str,
    model_name: str = "ALICE",
    encoders_path: str | None = None,
    features_path: str | None = None,
) -> str:
    """Enregistre un modele ALICE dans MLflow Registry.

    Args:
    ----
        model_path: Chemin vers le modele (AutoGluon ou baseline)
        model_name: Nom dans le registry
        encoders_path: Chemin vers les label encoders
        features_path: Chemin vers la liste des features

    Returns:
    -------
        URI du modele enregistre
    """
    import mlflow

    from scripts.serving.pyfunc_wrapper import AliceModelWrapper

    artifacts = _build_artifacts(model_path, encoders_path, features_path)
    signature = _build_mlflow_signature(mlflow)

    with mlflow.start_run():
        model_info = mlflow.pyfunc.log_model(
            artifact_path="alice_model",
            python_model=AliceModelWrapper(),
            artifacts=artifacts,
            signature=signature,
            registered_model_name=model_name,
        )

    logger.info("Model registered: %s", model_info.model_uri)
    return model_info.model_uri


def _build_artifacts(
    model_path: str, encoders_path: str | None, features_path: str | None
) -> dict[str, str]:
    """Build MLflow artifacts dict."""
    artifacts = {"model_path": model_path}
    if encoders_path:
        artifacts["encoders_path"] = encoders_path
    if features_path:
        artifacts["features_path"] = features_path
    return artifacts


def _build_mlflow_signature(mlflow: object) -> object:
    """Build MLflow model signature for ALICE features."""
    import mlflow as _mlflow

    input_schema = _mlflow.types.Schema(
        [
            *[_mlflow.types.ColSpec("double", f) for f in NUMERIC_FEATURES],
            *[_mlflow.types.ColSpec("string", f) for f in CATEGORICAL_FEATURES],
        ]
    )
    output_schema = _mlflow.types.Schema([_mlflow.types.ColSpec("double", "probability")])
    return _mlflow.models.signature.ModelSignature(inputs=input_schema, outputs=output_schema)


def create_render_deployment_config(
    model_uri: str,
    output_path: str = "render.yaml",
) -> None:
    """Cree la configuration de deploiement Render.

    Args:
    ----
        model_uri: URI du modele MLflow
        output_path: Chemin du fichier de configuration
    """
    config = f"""# Render deployment configuration for ALICE Engine
# Generated by scripts/serving/deploy_utils.py

services:
  - type: web
    name: alice-engine
    runtime: python
    plan: starter
    buildCommand: |
      pip install mlflow[extras] catboost xgboost lightgbm autogluon
      mlflow models download -m "{model_uri}" -d models/alice
    startCommand: mlflow models serve -m models/alice -p 8080 --host 0.0.0.0
    envVars:
      - key: MLFLOW_TRACKING_URI
        value: ./mlruns
      - key: PORT
        value: 8080
    healthCheckPath: /health
    autoDeploy: false
"""

    with open(output_path, "w", encoding="utf-8") as f:
        f.write(config)

    logger.info("Render config created: %s", output_path)
