"""ALICE Engine data validation schemas.

ISO Compliance:
- ISO/IEC 5259:2024 - Data Quality for ML
- ISO/IEC 42001:2023 - AI Management System
"""

from schemas.training_schemas import (
    # FFE Regulatory Constants
    AGE_CATEGORIES,
    COMPETITION_TYPES,
    ECHIQUIER_JEUNES_HIGH_BOARDS,
    ECHIQUIER_MAX_ABSOLUTE,
    ECHIQUIER_MIN,
    ELO_FLOOR_FIDE,
    ELO_MAX_INITIAL,
    ELO_MAX_N4_PLUS,
    ELO_MAX_REASONABLE,
    ELO_MIN_ESTIME,
    FIDE_TITLES,
    MAX_SAMPLE_VALUES,
    NIVEAU_ELO_CUPS,
    NIVEAU_HIERARCHY,
    NIVEAU_HIERARCHY_MAX,
    NIVEAU_N4,
    QUALITY_VALIDATION_RATE_THRESHOLD,
    RONDE_MAX_ABSOLUTE,
    RONDE_MIN,
    VALID_GAME_SCORES_ADULTES,
    VALID_GAME_SCORES_ALL,
    VALID_GAME_SCORES_JEUNES_HIGH,
    VALID_GAME_SCORES_JEUNES_LOW,
    VALID_MATCH_POINTS,
    VALID_RESULT_SUMS,
    VALID_RESULT_TYPES,
    VALID_ZONES_ENJEU,
    # ISO 5259 Data Quality Structures
    DataLineage,
    ErrorSeverity,
    QualityMetrics,
    TrainingSchemaPermissive,
    TrainingSchemaStrict,
    ValidationError,
    ValidationReport,
    # Validation Functions
    compute_quality_summary,
    create_training_schema,
    get_expected_score_range,
    is_valid_niveau_for_elo,
    validate_training_data,
    validate_with_report,
)

__all__ = [
    # FFE Regulatory Constants
    "AGE_CATEGORIES",
    "COMPETITION_TYPES",
    "ECHIQUIER_JEUNES_HIGH_BOARDS",
    "ECHIQUIER_MAX_ABSOLUTE",
    "ECHIQUIER_MIN",
    "ELO_FLOOR_FIDE",
    "ELO_MAX_INITIAL",
    "ELO_MAX_N4_PLUS",
    "ELO_MAX_REASONABLE",
    "ELO_MIN_ESTIME",
    "FIDE_TITLES",
    "MAX_SAMPLE_VALUES",
    "NIVEAU_ELO_CUPS",
    "NIVEAU_HIERARCHY",
    "NIVEAU_HIERARCHY_MAX",
    "NIVEAU_N4",
    "QUALITY_VALIDATION_RATE_THRESHOLD",
    "RONDE_MAX_ABSOLUTE",
    "RONDE_MIN",
    "VALID_GAME_SCORES_ADULTES",
    "VALID_GAME_SCORES_ALL",
    "VALID_GAME_SCORES_JEUNES_HIGH",
    "VALID_GAME_SCORES_JEUNES_LOW",
    "VALID_MATCH_POINTS",
    "VALID_RESULT_SUMS",
    "VALID_RESULT_TYPES",
    "VALID_ZONES_ENJEU",
    # ISO 5259 Data Quality Structures
    "DataLineage",
    "ErrorSeverity",
    "QualityMetrics",
    "TrainingSchemaPermissive",
    "TrainingSchemaStrict",
    "ValidationError",
    "ValidationReport",
    # Validation Functions
    "compute_quality_summary",
    "create_training_schema",
    "get_expected_score_range",
    "is_valid_niveau_for_elo",
    "validate_training_data",
    "validate_with_report",
]
